[package]
name = "acorn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aligned = "0.4.2"
num_enum = "0.7.2"
thiserror = "1.0.58"
zerocopy = { version = "0.7.32", features = ["derive"] }
