[package]
name = "acorn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
crc = "3.2.1"
mockall = { version = "0.12.1", features = ["nightly"] }
serde = { version = "1.0.199", features = ["derive"] }
serde_repr = "0.1.19"
thiserror = "1.0.58"
