[package]
name = "acorn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.2.1"
memmap2 = "0.9.4"
mockall = { version = "0.12.1", features = ["nightly"] }
thiserror = "1.0.58"
zerocopy = { version = "0.7.32", features = ["derive"] }
